# Generated by Django 5.2.3 on 2025-07-02 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.FloatField()),
                ('descricao', models.TextField()),
                ('porcentagem_desconto', models.IntegerField(default=0, null=True)),
                ('categoria', models.CharField(choices=[('suplementos', 'Suplementos'), ('alimentos', 'Alimentos'), ('roupas', 'Roupas'), ('acessorios', 'Acessórios')], default='suplementos', max_length=50)),
            ],
        ),
    ]
