# Generated by Django 5.1 on 2024-08-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='Cliente',
            new_name='Nome',
        ),
        migrations.AddField(
            model_name='cliente',
            name='CEP',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='cliente',
            name='CPF',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AddField(
            model_name='cliente',
            name='Dt_nasc',
            field=models.DateTimeField(default=''),
        ),
        migrations.AddField(
            model_name='cliente',
            name='Email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='Endereco',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='Estado_sigla',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='cliente',
            name='Senha',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='Telefone_cel',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AddField(
            model_name='cliente',
            name='Telefone_fixo',
            field=models.CharField(default='', max_length=11, null=True),
        ),
    ]
