# Generated by Django 5.1 on 2024-08-17 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_cliente_cep_cliente_cpf_cliente_endereco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='Dt_nasc',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
    ]
