# Generated by Django 5.1 on 2024-08-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_rename_cliente_cliente_nome_cliente_cep_cliente_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='Dt_nasc',
            field=models.DateTimeField(default='0000-00-00'),
        ),
    ]
