# Generated by Django 5.1 on 2024-08-17 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_cliente_dt_nasc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='senha',
            new_name='Senha',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='CPF',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
