# Generated by Django 5.1 on 2024-08-19 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_rename_email_cliente_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='CEP',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='Endereco',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='Estado',
        ),
    ]
