# Generated by Django 5.1 on 2024-09-06 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0008_rename_image_produto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='Favorito',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='Promocao',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
