# Generated by Django 5.1.1 on 2024-09-12 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0009_produto_favorito_produto_promocao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='CPF',
            new_name='cpf',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='Dt_nasc',
            new_name='dt_nasc',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='Nome',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='Senha',
            new_name='senha',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='Telefone_celular',
            new_name='telefone_celular',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='Telefone_fixo',
            new_name='telefone_fixo',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='Descricao',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='Dt_fabricacao',
            new_name='dt_fabricacao',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='Dt_validade',
            new_name='dt_validade',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='Favorito',
            new_name='favorito',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='Imagem',
            new_name='imagem',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='Nome',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='Preco',
            new_name='preco',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='Promocao',
            new_name='promocao',
        ),
    ]
