# Generated by Django 5.1 on 2024-09-12 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0010_rename_cpf_cliente_cpf_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='cpf',
            new_name='CPF',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='dt_nasc',
            new_name='Dt_nasc',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='nome',
            new_name='Nome',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='senha',
            new_name='Senha',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='telefone_celular',
            new_name='Telefone_celular',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='telefone_fixo',
            new_name='Telefone_fixo',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='descricao',
            new_name='Descricao',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='dt_fabricacao',
            new_name='Dt_fabricacao',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='dt_validade',
            new_name='Dt_validade',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='favorito',
            new_name='Favorito',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='imagem',
            new_name='Imagem',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='nome',
            new_name='Nome',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='preco',
            new_name='Preco',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='promocao',
            new_name='Promocao',
        ),
    ]
