# Generated by Django 5.1 on 2024-09-26 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0014_cliente_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='Senha',
        ),
    ]
