# Generated by Django 5.1 on 2024-10-20 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0017_remove_cliente_telefone_fixo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('rua', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=20)),
                ('cep', models.CharField(max_length=8)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loja.cliente')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('rua', 'numero'), name='unique_rua_numero')],
            },
        ),
    ]
