# Generated by Django 5.1 on 2024-10-20 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0018_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='complemento',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='telefone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
