# Generated by Django 5.1 on 2024-10-20 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0019_alter_endereco_complemento_alter_endereco_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.cliente'),
        ),
    ]
