# Generated by Django 5.1 on 2024-10-24 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0020_alter_endereco_cliente'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='endereco',
            name='unique_rua_numero',
        ),
    ]
