# Generated by Django 5.1 on 2024-11-14 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0021_remove_endereco_unique_rua_numero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('categoria', models.CharField(choices=[('status_pedido', 'Status do pedido'), ('status_devolucao', 'Status da devolução'), ('mensagem_personalizada', 'Mensagem Personalizada')], max_length=50)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.cliente')),
            ],
        ),
    ]
