# Generated by Django 5.1 on 2024-11-16 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0023_notificacao_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='lida',
            field=models.BooleanField(default=False),
        ),
    ]
