# Generated by Django 5.1.1 on 2024-11-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0024_notificacao_lida'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='enviar_para_todos',
            field=models.BooleanField(default=False),
        ),
    ]
