# Generated by Django 5.1.1 on 2024-11-18 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0025_notificacao_enviar_para_todos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loja.cliente'),
        ),
    ]
