# Generated by Django 5.1 on 2024-11-20 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0026_alter_notificacao_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nometitular', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=100)),
                ('bandeira', models.CharField(max_length=50)),
                ('categoria', models.CharField(choices=[('debito', 'Débito'), ('credito', 'Crédito')], max_length=10)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loja.cliente')),
            ],
        ),
    ]
