# Generated by Django 5.1 on 2024-11-20 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0027_cartao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartao',
            old_name='categoria',
            new_name='tipo',
        ),
    ]
