# Generated by Django 5.1.3 on 2024-11-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0027_remove_produto_favorito_produto_estoque_carrinho_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='Estoque',
            field=models.IntegerField(default=1),
        ),
    ]
