# Generated by Django 5.1.3 on 2024-11-25 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0028_alter_produto_estoque'),
        ('loja', '0028_rename_categoria_cartao_tipo'),
    ]

    operations = [
    ]
