# Generated by Django 5.1 on 2024-11-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0028_rename_categoria_cartao_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='Favorito',
        ),
        migrations.AddField(
            model_name='produto',
            name='Estoque',
            field=models.IntegerField(default=10),
        ),
    ]
