# Generated by Django 5.1 on 2024-12-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0031_favorito'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='Categoria',
            field=models.CharField(choices=[('suplementos', 'Suplementos'), ('alimentos', 'Alimentos'), ('roupas', 'Roupas'), ('acessorios', 'Acessórios')], default='suplementos', max_length=50),
        ),
    ]
