# Generated by Django 5.1 on 2024-12-02 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0032_produto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='Descricao',
            field=models.TextField(),
        ),
    ]
