# Generated by Django 5.1 on 2024-12-02 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0029_merge_20241125_1645'),
        ('loja', '0032_produto_categoria'),
    ]

    operations = [
    ]
