# Generated by Django 5.1 on 2024-12-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0033_alter_produto_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='Imagem',
            field=models.ImageField(blank=True, upload_to='produtos/'),
        ),
    ]
