# Generated by Django 5.1.3 on 2024-12-03 16:14

import loja.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0033_merge_0029_merge_20241125_1645_0032_produto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='Estoque',
            field=models.IntegerField(default=10, validators=[loja.validators.numero_nao_negativo]),
        ),
    ]
