# Generated by Django 5.1 on 2024-12-05 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0034_alter_produto_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartao',
            old_name='nometitular',
            new_name='nome_titular',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='Promocao',
            new_name='Porcentagem_desconto',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='Dt_fabricacao',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='Dt_validade',
        ),
    ]
