# Generated by Django 5.1 on 2024-12-05 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0035_rename_nometitular_cartao_nome_titular_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='Categoria',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='Descricao',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='Estoque',
            new_name='estoque',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='Imagem',
            new_name='imagem',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='Nome',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='Porcentagem_desconto',
            new_name='porcentagem_desconto',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='Preco',
            new_name='preco',
        ),
    ]
