# Generated by Django 5.1 on 2024-12-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0037_rename_cpf_cliente_cpf_rename_nome_cliente_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='perfil',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'Usuário')], default='user', max_length=10),
        ),
    ]
