# Generated by Django 5.1 on 2025-01-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0042_carrinhoitem_imagem_alter_carrinho_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
