# Generated by Django 5.1 on 2025-01-22 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0047_pedidoitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='loja.produto'),
        ),
    ]
