# Generated by Django 5.1 on 2025-01-22 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0048_alter_lote_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('1', 'Processando'), ('2', 'Enviado'), ('3', 'Entregue'), ('4', 'Recebido')], default='1', max_length=50),
            preserve_default=False,
        ),
    ]
