# Generated by Django 5.1 on 2025-01-28 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0049_pedido_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cartao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='loja.cartao'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='endereco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='loja.endereco'),
        ),
    ]
