# Generated by Django 5.1 on 2025-01-28 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0051_alter_pedido_cartao_alter_pedido_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorito',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='loja.cliente'),
        ),
        migrations.AlterField(
            model_name='favorito',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='loja.produto'),
        ),
    ]
