# Generated by Django 5.1 on 2025-01-31 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0053_avaliacaoproduto'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevolucaoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('data_devolucao', models.DateTimeField(auto_now_add=True)),
                ('foto_video', models.FileField(blank=True, null=True, upload_to='devolucoes/')),
                ('status', models.CharField(choices=[('1', 'em análise'), ('2', 'aprovado'), ('3', 'reprovado')], max_length=50)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devolucoes', to='loja.produto')),
            ],
        ),
    ]
