# Generated by Django 5.1 on 2025-01-31 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0054_devolucaoproduto'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucaoproduto',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='devolucoes', to='loja.cliente'),
            preserve_default=False,
        ),
    ]
