# Generated by Django 5.1 on 2025-02-12 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0055_devolucaoproduto_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='loja.cliente'),
        ),
    ]
