# Generated by Django 5.1 on 2025-02-13 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0056_alter_notificacao_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacao',
            name='enviar_para_todos',
        ),
    ]
