from .HomeView import *
from .user.PromocoesView import *
from .user.CadastroView import *
from .user.LoginView import *
from .user.AvaliarProdutoView import *
from .user.CarrinhoView import *
from .user.CarteiraView import *
from .user.CategoriaView import *
from .user.ComprarNovamenteView import *
from .user.DevolverProdutoView import *
from .user.EnderecoView import *
from .user.FavoritoView import *
from .user.MaisVendidosView import *
from .user.MeusFavoritosView import *
from .user.MeusPedidosView import *
from .user.NotificacoesView import *
from .user.FinalizarPedidoView import *
from .user.PerfilView import *
from .user.ProdutoView import *
from .admin.ProdutosView import *